### ISSUE TITLE
Add CONTRIBUTORS.md and Code of Conduct

### ISSUE THREAD

**Issue by rufusraghunath** [rufusraghunath/kelda#2]

**Comment by binkley** [comment]
There are various other GitHub files also, depending on your contributor model:  https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

**Comment by rufusraghunath** [comment]
Fixed by acc4e11df1ed58c25d4fe9ea2ebaa9b6d11376cc and b6725d17f2cf6f9c5419fc901de32ee7d6242c5f
